# Generated by Django 4.2.3 on 2023-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('periodo', models.DateTimeField(verbose_name='periodo de ingresso')),
                ('nota', models.CharField(max_length=3, verbose_name='nota')),
                ('situacao', models.TextField(verbose_name='situação')),
            ],
        ),
    ]
